const sampleData = [
  // 🔹 Internship Data
  {
    category: "Internship",
    title: "Frontend Developer Intern",
    description: "Work on building responsive UI using React.",
    company: "TechNova",
    location: "Remote",
    link: "https://technova.com/internship",
    deadline: new Date("2026-04-10"),
    stipend: 10000,
    workMode: "remote",
  },
  {
    category: "Internship",
    title: "Backend Developer Intern",
    description: "Develop APIs using Node.js and Express.",
    company: "CodeCraft",
    location: "Bangalore",
    link: "https://codecraft.com/internship",
    deadline: new Date("2026-04-15"),
    stipend: 12000,
    workMode: "offline",
  },
  {
    category: "Internship",
    title: "Full Stack Intern",
    description: "Work on MERN stack projects.",
    company: "DevHub",
    location: "Pune",
    link: "https://devhub.com/internship",
    deadline: new Date("2026-04-20"),
    stipend: 15000,
    workMode: "online",
  },
  {
    category: "Internship",
    title: "UI/UX Intern",
    description: "Design user-friendly interfaces and prototypes.",
    company: "DesignPro",
    location: "Remote",
    link: "https://designpro.com/internship",
    deadline: new Date("2026-04-25"),
    stipend: 8000,
    workMode: "remote",
  },
  {
    category: "Internship",
    title: "Data Analyst Intern",
    description: "Analyze datasets and create dashboards.",
    company: "DataWorks",
    location: "Mumbai",
    link: "https://dataworks.com/internship",
    deadline: new Date("2026-04-30"),
    stipend: 14000,
    workMode: "offline",
  },

  // 🔹 Hackathon Data
  {
    category: "Hackathon",
    title: "AI Innovation Challenge",
    description: "Build AI solutions for real-world problems.",
    company: "Google Devs",
    location: "Online",
    link: "https://aihackathon.com",
    deadline: new Date("2026-05-05"),
    prize: 50000,
    teamSize: 4,
  },
  {
    category: "Hackathon",
    title: "Smart India Hackathon",
    description: "Solve government problem statements.",
    company: "Govt of India",
    location: "Delhi",
    link: "https://sih.gov.in",
    deadline: new Date("2026-05-10"),
    prize: 100000,
    teamSize: 6,
  },
  {
    category: "Hackathon",
    title: "Web3 Hackathon",
    description: "Build decentralized applications.",
    company: "Polygon",
    location: "Remote",
    link: "https://web3hack.com",
    deadline: new Date("2026-05-12"),
    prize: 75000,
    teamSize: 3,
  },
  {
    category: "Hackathon",
    title: "Startup Hackathon",
    description: "Create startup ideas and MVPs.",
    company: "Startup India",
    location: "Mumbai",
    link: "https://startuphack.com",
    deadline: new Date("2026-05-18"),
    prize: 60000,
    teamSize: 5,
  },
  {
    category: "Hackathon",
    title: "Cybersecurity Hackathon",
    description: "Solve cybersecurity challenges.",
    company: "CyberSafe",
    location: "Bangalore",
    link: "https://cyberhack.com",
    deadline: new Date("2026-05-22"),
    prize: 80000,
    teamSize: 4,
  },

  // 🔹 Placement Data
  {
    category: "Placement",
    title: "Software Engineer",
    description: "Develop scalable backend systems.",
    company: "Infosys",
    location: "Hyderabad",
    link: "https://infosys.com/careers",
    deadline: new Date("2026-06-01"),
    salary: 600000,
    jobRole: "Backend Developer",
    cgpaCriteria: 7.0,
  },
  {
    category: "Placement",
    title: "Frontend Developer",
    description: "Work on UI development ucsing React.",
    company: "TCS",
    location: "Pune",
    link: "https://tcs.com/careers",
    deadline: new Date("2026-06-05"),
    salary: 500000,
    jobRole: "Frontend Developer",
    cgpaCriteria: 6.5,
  },
  {
    category: "Placement",
    title: "Full Stack Developer",
    description: "Work on both frontend and backend.",
    company: "Wipro",
    location: "Bangalore",
    link: "https://wipro.com/careers",
    deadline: new Date("2026-06-10"),
    salary: 700000,
    jobRole: "Full Stack Developer",
    cgpaCriteria: 7.5,
  },
  {
    category: "Placement",
    title: "Data Scientist",
    description: "Analyze and interpret complex data.",
    company: "Accenture",
    location: "Mumbai",
    link: "https://accenture.com/careers",
    deadline: new Date("2026-06-15"),
    salary: 900000,
    jobRole: "Data Scientist",
    cgpaCriteria: 8.0,
  },
  {
    category: "Placement",
    title: "System Engineer",
    description: "Maintain IT systems and infrastructure.",
    company: "HCL",
    location: "Chennai",
    link: "https://hcl.com/careers",
    deadline: new Date("2026-06-20"),
    salary: 550000,
    jobRole: "System Engineer",
    cgpaCriteria: 6.0,
  },
];

module.exports = sampleData;